# Generated by Django 2.0.13 on 2019-03-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto_paciente',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes_fotos'),
        ),
    ]
